# Generated by Django 4.2 on 2026-02-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активный'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('required_hard_skills', models.ManyToManyField(limit_choices_to={'skill_type': 'hard'}, related_name='required_for_requests', to='profiles.skill')),
                ('required_soft_skills', models.ManyToManyField(blank=True, limit_choices_to={'skill_type': 'soft'}, related_name='required_for_requests_soft', to='profiles.skill')),
            ],
            options={
                'verbose_name': 'Запрос на сотрудничество',
                'verbose_name_plural': 'Запросы на сотрудничество',
                'ordering': ['-created_at'],
            },
        ),
    ]
